apiVersion: v1
kind: Service
metadata:
  name: gallery-exhibitions
spec:
  type: ClusterIP
  ports:
    - name: "gallery-exhibitions"
      port: 8081
      targetPort: 8081
  selector:
    app: gallery-exhibitions