apiVersion: v1
kind: Service
metadata:
  name: gallery-gw
spec:
  type: ClusterIP
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 7080
      targetPort: 7080
  selector:
    app: gallery-gw