apiVersion: v1
kind: Service
metadata:
  name: gallery-visitors
spec:
  type: ClusterIP
  ports:
    - name: "gallery-visitors"
      port: 8084
      targetPort: 8084
  selector:
    app: gallery-visitors