apiVersion: v1
kind: Service
metadata:
  name: gallery-workers
spec:
  type: ClusterIP
  ports:
    - name: "gallery-workers"
      port: 8085
      targetPort: 8085
  selector:
    app: gallery-workers