apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery-workers
  template:
    metadata:
      labels:
        app: gallery-workers
    spec:
      containers:
        -
          image: evakolds/worker
          name: gallery-workers
          ports:
            - containerPort: 8085
              name: rest
            - containerPort: 7085
              name: grpc